### ISSUE TITLE
User can login to their account on the login page

### ISSUE THREAD

**Issue by aNewbieProgrammer** [Pow-Wow-CS490/Pow-Wow#27]
- [ ] User can enter their username in the "enter username" section (on the login page)
- [ ] User can enter their password in the "enter password" section (on the login page)
- [ ] User can click the "login" button (on the login page) to navigate to the feed
- [ ] User can see an error message "Username or password incorrect. Please try again.", if login credentials are incorrect.

**Comment by jacksonmccluskey** [comment]
Duplicate
